config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users/create'
  get 'profile', to: 'users#show'

  get 'session/login'
  post 'session/create'
  get 'session/logout'

  resources :posts, only: [ :index, :edit, :update, :new, :create, :destroy ]

  resources :requests, only: [ :edit, :update, :new, :create, :destroy ]
  get 'request/update/take', to: 'requests#update_status_to_took'
  get 'request/update/finish', to: 'requests#update_status_to_finished'

  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#view"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :council_member
  validates_presence_of :title, message: 'У сообщения должен быть заголовок'
  validates_presence_of :text, message: 'Сообщение не может быть пустым'
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# Messages controller
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
    @messages = Message.all
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit; end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    if @message.update(message_params)
      redirect_to messages_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    redirect_to messages_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).merge(council_member_id: @_current_user_role.id).permit(:title, :text,
                                                                                     :council_member_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div class="row m-3">
    <div class="col-4">
        <%= form_with(model: message) do |form| %>
            <% if message.errors.any? %>
                <div style="color: red">
                    <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

                    <ul>
                        <% message.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="mb-3">
                <%= form.label :title, 'Заголовок', class: 'form-label' %>
                <%= form.text_field :title, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <%= form.label :text, 'Текст', class: 'form-label' %>
                <%= form.text_field :text, class: 'form-control' %>
            </div>

            <div>
                <%= form.submit value: 'Добавить', class: 'btn btn-primary col-md-6' %>
            </div>
        <% end %>
        <div class="mt-5">
            <%= link_to 'Назад', messages_path, class: 'btn btn-primary col-md-6'%>
        </div>
    </div>
</div>

app/views/messages/_message.html.erb
<p> <%= message.title %>: <%= message.text %></p>

app/views/messages/_show.html.erb
<% Message.all.each do |message| %>
    <div class="text-center bg-warning bg-gradient mb-1">
        <%= render message %>
    </div>
<% end %>

app/views/messages/edit.html.erb
<div class="row m-1">
    <h2>Редактировать</h2>
</div>

<%= render "form", message: @message %>

app/views/messages/index.html.erb
<div class="row mb-5 mr-1">
    <h1>Сообщения</h1>
</div>

<% @messages.each do |message| %>
    <div class="col-4 mb-5 border border-2">
        <div class="row m-3">
            <div class="col-6">
                <%= render message %>
            </div>
            <div class="col-6 text-center">
                <%= link_to "Изменить", edit_message_path(message) %>
                <%= button_to "Удалить сообщение", message, method: :delete, class: 'btn btn-primary mt-2' %>
            </div>
        </div>
    </div>
<% end %>

<div class="col-4">
    <div class="row m-3">
        <div class="col-6">
            <%= link_to "Добавить сообщение", new_message_path, class: 'btn btn-primary' %>
        </div>
        <div class="col-6">
            <%= link_to "Назад", profile_path, class: 'btn btn-primary' %>
        </div>
    </div>
</div>

app/views/messages/new.html.erb
<div class="row m-1">
    <h2>Добавить сообщение</h2>
</div>

<%= render "form", message: @message %>