config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users/create'
  get 'profile', to: 'users#show'

  get 'session/login'
  post 'session/create'
  get 'session/logout'

  resources :posts, only: [ :index, :edit, :update, :new, :create, :destroy ]

  resources :requests, only: [ :edit, :update, :new, :create, :destroy ]
  get 'request/update/take', to: 'requests#update_status_to_took'
  get 'request/update/finish', to: 'requests#update_status_to_finished'

  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#view"
end

app/controllers/session_controller.rb
# frozen_string_literal: true

# Sessions controller
class SessionController < ApplicationController
  skip_before_action :authenticate, only: %i[login create]

  def login; end

  def create
    user = User.find_by_login(params[:login])
    if user&.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = user.nil? ? 'Неправильный логин' : 'Неправильный пароль'
      redirect_to session_login_path
    end
  end

  def logout
    session.delete(:current_user_id)
    @_current_user = nil
    @_user_access = nil
    @_current_user_role = nil
    redirect_to session_login_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/login.html.erb
<div class="row text-center">
    <div class="col-4"></div>
    <div class="col-4">
        <h1 class="h3 mb-3 font-weight-normal">Добро пожаловать!</h1>
        <h1 class="h3 mb-3 font-weight-normal">Войдите, чтобы продолжить</h1>
        <h3 class="text-center" style="color: green" id="success-message"><%= notice %></h3>
        <h3 class="text-center" style="color: red" id="error-message"><%= alert %></h3>
        <%= form_with url: session_create_path, method: :post, local: true, class: 'form-signin' do |form| %>
            <div class="mb-3">
                <%= form.label :login, 'Логин: ' , class: 'form-label' %>
                <%= form.text_field :login, require: true, class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= form.label :num, 'Пароль: ', class: 'form-label' %>
                <%= form.password_field :password, require: true, class: 'form-control'%>
            </div>
            <%= form.submit value: 'Войти', require: true, class: 'btn btn-primary col-md-12' %>
        <% end %>
    </div>
    <div class="col-4"></div>
</div>
<br>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <p class="text-center">Еще нет аккаунта?</p>
        <%= link_to 'Регистрация', users_new_path, class: 'btn btn-primary col-md-12' %>
    </div>
    <div class="col-4"></div>
</div>