config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users/create'
  get 'profile', to: 'users#show'

  get 'session/login'
  post 'session/create'
  get 'session/logout'

  resources :posts, only: [ :index, :edit, :update, :new, :create, :destroy ]

  resources :requests, only: [ :edit, :update, :new, :create, :destroy ]
  get 'request/update/take', to: 'requests#update_status_to_took'
  get 'request/update/finish', to: 'requests#update_status_to_finished'

  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#view"
end

app/models/user.rb
class User < ApplicationRecord
  has_one :student

  has_one :staff

  validates_uniqueness_of :login, message: 'Имя пользователя уже существует'
  validates_presence_of :login, message: 'Укажите логин'

  has_secure_password
  validates_presence_of :password, message: 'Пароль пользователя не должно быть пустым'
  validates_length_of :password, minimum: 6, message: 'Пароль должен быть 6 или более символов'
  validates_confirmation_of :password, message: 'Пароли различны'
  validates_each :password do |record, attr, value|
    record.errors.add(attr, message: 'Пароль должен содержать цифры') unless value =~ /\d/
    record.errors.add(attr, message: 'Пароль должен содержать строчные буквы') unless value =~ /[a-z]/
    record.errors.add(attr, message: 'Пароль должен содержать прописные буквы') unless value =~ /[A-Z]/
  end

  validates_presence_of :name, message: 'Укажитие имя'

  validates_presence_of :surname, message: 'Укажитие фамилию'
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller
class UsersController < ApplicationController
  before_action :parse_user_type, only: :create
  skip_before_action :authenticate, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.invalid?
      render :new, status: :unprocessable_entity
      return
    end

    @user.save
    student = Student.new(user_id: @user.id, room: params[:user][:room])
    staff = Staff.new(user_id: @user.id, rank: params[:user][:rank])

    if @user_type == 'student' && student.save
      redirect_to session_login_path, notice: 'Пользователь успешно создан'
    elsif @user_type == 'staff' && staff.save
      redirect_to session_login_path, notice: 'Пользователь успешно создан'
    else
      render :new, status: :unprocessable_entity
      @user.destroy
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation, :name, :surname, :second_name)
  end

  def parse_user_type
    @user_type = params[:user][:user_type]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_staff_requests.html.erb
<h3 class="text-center">Заявки</h3>
<% Request.all.each do |request| %>
    <% if request.staff_id == @_current_user_role.id && request.status != 'Завершена' %>
        <div class="row">
            <div class="col-6">
                <p>Этаж:  <%= request.floor%></p>
                <p>Место: <%= request.location %></p>
                <p>Проблема: <%= request.problem %></p>
            </div>
            <div class="col-6">
                <div class="text-center mt-3">
                    <% if request.status == 'Не рассмотрено' %>
                        <%= form_with(url: request_update_take_path, method: :get) do |form| %>
                            <input type="text" value="<%= request.id %>" name="id" style="visibility: hidden">
                            <%= form.submit value: 'Взять', class: 'btn btn-primary' %>
                        <% end %>
                    <% end %>
                    <% if request.status == 'В работе' %>
                        <%= form_with(url: request_update_finish_path, method: :get) do |form| %>
                            <input type="text" value="<%= request.id %>" name="id" style="visibility: hidden">
                            <%= form.submit value: 'Завершить', class: 'btn btn-primary' %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/users/_student_requests.html.erb
<h3 class="text-center">Мои заявки</h3>
<%= link_to "Отправить заявку", new_request_path, class: 'btn btn-primary col-md-12' %>
<% Request.all.each do |request| %>
    <% if request.student_id == Student.find_by_user_id(@_current_user.id).id%>
        <p><%= render request %></p>
    <% end %>
<% end %>

app/views/users/new.html.erb
<div class="row m-1">
    <h2>Регистрация</h2>
</div>

<div class="row m-3">
    <div class="col-4">
        <%= form_with(model: @user, url: users_create_path) do |form| %>
            <div class="mb-3">
                <% if @user.errors[:login].any? %>
                    <div style="color: red" class="fst-italic fw-light" id="errors-login">
                        <% @user.errors[:login].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :login, 'Логин: ', class: 'form-label' %>
                <%= form.text_field :login, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <% if @user.errors[:password].any? %>
                    <div style="color: red" class="fst-italic fw-light" id="errors-password">
                        <% @user.errors[:password].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :password, 'Пароль: ', class: 'form-label' %>
                <%= form.password_field :password, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <% if @user.errors[:password_confirmation].any? %>
                    <div style="color: red" class="fst-italic fw-light" id="errors-password-confirmation">
                        <% @user.errors[:password_confirmation].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :password_confirmation, 'Повторите пароль: ', class: 'form-label' %>
                <%= form.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <% if @user.errors[:name].any? %>
                    <div style="color: red" class="fst-italic fw-light" id="errors-name">
                        <% @user.errors[:name].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :name, 'Имя: ', class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <% if @user.errors[:surname].any? %>
                    <div style="color: red" class="fst-italic fw-light" id="errors-surname">
                        <% @user.errors[:surname].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :surname, 'Фамилия: ', class: 'form-label' %>
                <%= form.text_field :surname, class: 'form-control' %>
            </div>

            <div class="mb-5">
                <% if @user.errors[:second_name].any? %>
                    <div style="color: red" class="fst-italic fw-light">
                        <% @user.errors[:second_name].each do |error| %>
                            <p><%= error %></p>
                        <% end %>
                    </div>
                <% end %>
                <%= form.label :second_name, 'Отчество: ', class: 'form-label' %>
                <%= form.text_field :second_name, class: 'form-control' %>
            </div>

            <div class="mb-5">
                <p class="fst-italic fw-light">При регистрации как студент укажите комнату</p>
            </div>

            <div class="mb-3">
                <%= form.radio_button :user_type, 'student', class: 'form-check-input' %>
                <%= form.label :side, 'Зарегистрироваться как студент', class: 'form-label' %>
            </div>

            <div class="mb-5">
                <%= form.label :room, 'Комната: ', class: 'form-label' %>
                <%= form.text_field :room, class: 'form-control' %>
            </div>
            
            <div class="mb-5">
                <p class="fst-italic fw-light">При регистрации как работник укажите должность</p>
            </div>

            <div class="mb-3">
                <%= form.radio_button :user_type, 'staff', class: 'form-check-input' %>
                <%= form.label :side, 'Зарегистрироваться как сотрудник', class: 'form-label' %>
            </div>

            <div class="mb-3">
                <%= form.label :rank, 'Должность: ', class: 'form-label' %>
                <%= form.text_field :rank, class: 'form-control' %>
            </div>

            <div>
                <%= form.submit value: 'Зарегистрироваться', class: 'btn btn-primary col-md-12' %>
            </div>
        <% end %>
        <div class="mt-5">
            <%= link_to 'Назад', session_login_path, class: 'btn btn-primary col-md-6'%>
        </div>
    </div>
    <div class="col-7"></div>
</div>

app/views/users/show.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">МоёОбщежитие</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to 'Главная', root_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Новости', posts_path, class: 'nav-link' %>
                    </li>
                </ul>
                <%= link_to 'Личный кабинет', profile_path, class: 'btn btn-primary' %>        
            </div>
        </div>
    </nav>
    <%= render "messages/show" if @_user_access != ApplicationController::STAFF %>
</header>

<div class="row mt-3 container">
    <div class="col-1"></div>
    <div class="col-5">
        <h2>Пользователь</h2>
        <p>Фамилия: <%= @_current_user.surname %></p>
        <p>Имя: <%= @_current_user.name %></p>
        <p>Отчество: <%= @_current_user.second_name %></p>
        <%= link_to 'Выйти', session_logout_path, class: 'btn btn-primary col-md-4' %>
        <%= link_to 'Менеджер сообщений', messages_path, class: 'btn btn-primary' if @_user_access == ApplicationController::COUNCIL_MEMBER%>
    </div>

    <div class="col-5 border border-1">
        <!-- Заявки для студентов -->
        <% if @_user_access >= ApplicationController::STUDENT %>
            <%= render "student_requests" %>
        <% end %>

        <!-- Заявки для работников -->
        <% if @_user_access == ApplicationController::STAFF %>
            <%= render "staff_requests" %>
        <% end %>
    </div>
</div>