config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users/create'
  get 'profile', to: 'users#show'

  get 'session/login'
  post 'session/create'
  get 'session/logout'

  resources :posts, only: [ :index, :edit, :update, :new, :create, :destroy ]

  resources :requests, only: [ :edit, :update, :new, :create, :destroy ]
  get 'request/update/take', to: 'requests#update_status_to_took'
  get 'request/update/finish', to: 'requests#update_status_to_finished'

  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#view"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :council_member
  validates_presence_of :title, message: 'У новости должен быть заголовок'
  validates_presence_of :text, message: 'Новость не может быть пустой'
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Posts controller
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :check_access, only: %i[new create edit update]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.fetch(:post, {}).merge({ council_member_id: @_current_user_role.id }).permit(:title, :text,
                                                                                        :council_member_id)
  end

  def check_access
    redirect_to posts_path, alert: 'Нет доступа' if @_user_access != ApplicationController::COUNCIL_MEMBER
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row m-3">
    <div class="col-4">
        <%= form_with(model: post) do |form| %>
            <% if post.errors.any? %>
                <div style="color: red">
                    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

                    <ul>
                        <% post.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="mb-3">
                <%= form.label :title, 'Заголовок', class: 'from-label' %>
                <%= form.text_field :title, require: true, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <%= form.label :text, 'Текст', class: 'form-label' %>
                <%= form.text_area :text, require: true, class: 'form-control', style: 'height: 300px' %>
            </div>

            <div>
                <%= form.submit value: 'Добавить новость', class: 'btn btn-primary col-md-6' %>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/_post.html.erb
<div>
    <h3><%= post.title %></h3>
    <p class="fst-italic fw-light"><%= post.created_at %></p>
    <p><%= post.text %></p>
</div>

app/views/posts/edit.html.erb
<h1>Редактировать</h1>

<%= render "form", post: @post %>

<br>

<div class="m-4">
  <%= link_to "Назад", posts_path, class: 'btn btn-primary col-md-2' %>
</div>

app/views/posts/index.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">МоёОбщежитие</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to 'Главная', root_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Новости', posts_path, class: 'nav-link active' %>
                    </li>
                </ul>
                <%= link_to 'Личный кабинет', profile_path, class: 'btn btn-primary' %>        
            </div>
        </div>
    </nav>
    <%= render "messages/show" if @_user_access != ApplicationController::STAFF %>
</header>

<% if @_user_access == ApplicationController::COUNCIL_MEMBER %>
    <%= link_to "Добавить новость", new_post_path, class: 'btn btn-primary col-auto m-3' %>
<% end %>

<h1 class="m-3">Новости</h1>

<article class="m-3">

    <% @posts.order(created_at: :desc).each do |post| %>
        <div class="row">
            <article class="border border-2 col-8 m-3">
                <%= render post %>

                <% if @_user_access == ApplicationController::COUNCIL_MEMBER %>
                    <p><%= link_to 'Редактировать', edit_post_path(post), class: 'col-1' %></p>
                    <%= button_to "Удалить новость", post, method: :delete, class: 'btn btn-primary mb-2' %>
                <% end %>
            </article>
        </div>
    <% end %>

</article>

app/views/posts/new.html.erb
<div class="row m-1">
    <h2>Добавить новость</h2>
</div>

<%= render "form", post: @post %>

<br>

<div class="m-4">
  <%= link_to "Назад к новостям", posts_path, class: 'btn btn-primary col-md-2' %>
</div>